### ISSUE TITLE
Use bootstrap dropdown for language selector

### ISSUE THREAD

**Issue by evfool** [themefisher/meghna-hugo#106]
The select component seems a bit out of place for language selection, in my opinion a bootstrap dropdown looks better.
![dropdown](https://user-images.githubusercontent.com/443993/82866876-6df25280-9f32-11ea-8c01-46d6f8ca449c.png)
![select](https://user-images.githubusercontent.com/443993/82866889-76e32400-9f32-11ea-94a8-8a44097e79af.png)

If you think it would be useful, I could prepare a merge request easily.

**Comment by somrat-gyver** [comment]
Hey there, make a pull request. if it looks ok, then I will marge it. thanks for being with themefisher.
