### ISSUE TITLE
How do I keep the same excerpt box for latest posts?

### ISSUE THREAD

**Issue by Zephir1425** [themefisher/meghna-hugo#11]
I love your theme, but on the latest posts section, with my own posts, the boxes are not the same height, it seems that more texts is allowed in the excerpts for some posts compared to others creating the imbalance. How can I fix it?  See screenshot below
![image](https://user-images.githubusercontent.com/45423031/50049303-251f5300-011d-11e9-95f4-733b2b454ef3.png)

**Comment by mehedi-sharif** [comment]
Hello @Zephir1425 ,
You can do two things here . One is css hack and another one is from hugo excerpt limit . for css hack please check this https://stackoverflow.com/questions/37316308/using-html-css-to-limit-the-length-of-the-sentences .
and for hugo please check https://discourse.gohugo.io/t/limit-the-summary/4103/11. 
Basically you need to use summarylength = 30.
Thanks

**Comment by Zephir1425** [comment]
Thanks. I have actually ended up using "{{slicestr .Summary 3 200 | markdownify }}" in the blog.html. It works well for the actual content excerpt. However, I still have an issue with the titles (according to their size, they go on on 2 or 3 rows, I have not yet figured out how to fix it.

**Comment by mehedi-sharif** [comment]
Can you show a screenshot . Normally no one uses 2/3 line title.

**Comment by Zephir1425** [comment]
sure. Here it is
![image](https://user-images.githubusercontent.com/45423031/50945594-5dbe0c80-14d0-11e9-8546-f4851cce9b95.png)

**Comment by mehedi-sharif** [comment]
I think you can use `min-height:400px` this css property to give all the boxes a minimum height.
