### ISSUE TITLE
Migrate to NetlifyCMS

### ISSUE THREAD

**Issue by OdairTrujillo** [themefisher/meghna-hugo#111]
Recently I found myself forced to drop Forestry.io in favor of NetlifyCMS due to some problems on Forestry.io, regardless of user registration. Fortunately, the problem in Forestry.io is solved by now, but I felt that the project it's not moving fast enough.

On the other hand, NetlifyCMS works very well, you don't need additional third-party services like Forestry, can invite users, use google authentication, etc. Sure you already know about it. But if you're interested, I have my configuration working in production and we can make a new branch to test this.

I feel that the only limitation could be the extra configuration inside the Netlify platform, but we can look if we can automate the process with Netlify plugins.

Thanks for your attention.

**Comment by somrat-gyver** [comment]
Hey there, you can make a pull request with netlify settings added. thanks.

**Comment by somratpro** [comment]
Hello @OdairTrujillo,

I have tried the netlify CMS and found out that it's not convenient for our users. So we will be strict with Forestry for now.
