### ISSUE TITLE
Current version doesn't work at all.

### ISSUE THREAD

**Issue by Radamant24** [themefisher/meghna-hugo#113]
Hi, I tried to deploy the current version using netlify + forestry as explained in the [tutorial video](https://www.youtube.com/watch?v=ResipmZmpDU&feature=youtu.be) 

But it didn't work.  

I had to rollback to some older commits (20 days ago) and then it worked.

The error is:

`Error: module "Meghna-Hugo" not found; either add it as a Hugo Module or store it in "/opt/build".: module does not exist`

I would appreciate if you solve it and test it using netlify + forestry, as I really want to use the latest version always.

Thanks and keep up the good work

**Comment by developer-evan** [comment]
Hey there, I have fixed this issue, you can go on with Meghna Hugo now...
