### ISSUE TITLE
Migrating css/js from static to assets ?

### ISSUE THREAD

**Issue by divinerites** [themefisher/meghna-hugo#114]
Hello Mehedi,

I will use Meghna theme to rewrite my first use of your theme (first version of airspace).

As i have experience the rewrite from `/static` to `/assets` for the themes I use (timer and navigator mainly), I was looking to make this basic work before migrating the airspace site.

So I was wondering if you're interested in this work to incorporate in your free theme ? or you prefer not to include it for any (business or technical) reason. If yes, I could work on this in a clean way and then make a PR.

The purpose of this work -associated with a [lazyload](https://github.com/verlok/vanilla-lazyload) small lib-  is to gain really really fast load and test notes, so ranking and loading user experience are better

**Comment by divinerites** [comment]
Sorry for the noise. Do not know why i was thinking it was not already uses as assets. Sorry for the noise.

It is images that are served from static.

**Comment by divinerites** [comment]
2 small questions :
- Is there a technical reason for some css (plugins, custom) being served from static and not treated as asset like others ?
- Same question for images, not being processed as assets with the optimisation benefits, and automatic width/height, etc ...

**Comment by developer-evan** [comment]
no, there is no technical reason. thanks

**Comment by developer-evan** [comment]
I am going to close this issue, if you have more concerns then create a new issue. thanks for being with themefisher.
