### ISSUE TITLE
Error in layouts/partials/footer.html, line 41

### ISSUE THREAD

**Issue by cdichiara** [themefisher/meghna-hugo#126]
@divinerites seems to have left off a closing }

**Comment by divinerites** [comment]
Yes. Sorry, someone already made a PR : https://github.com/themefisher/meghna-hugo/pull/123

I tested on a private branch and (badly) copied the modifications. Again sorry for that.

**Comment by developer-evan** [comment]
I have merged this PR, also if you like our template then don't forget to give us a star, it will encourage us to build new template.
