### ISSUE TITLE
Couldn't view CSS

### ISSUE THREAD

**Issue by Angeline-neo** [themefisher/meghna-hugo#129]
<img width="1614" alt="Screen Shot 2020-07-13 at 9 55 32 AM" src="https://user-images.githubusercontent.com/59534929/87263244-25492580-c4ef-11ea-8c56-c53164461957.png">

Hi,

I followed every step on the video but my CSS is not showing up. What should I do?

**Comment by developer-evan** [comment]
Hey there, you might miss the baseURL match. remember that, you need to give the same baseURL in netlify and forestry. 

Also if you like this template, a star would be amazing. thanks for being with themefisher.
