### ISSUE TITLE
Fix section titles in layouts/partials/*.html

### ISSUE THREAD

**Issue by gdsantoro** [themefisher/meghna-hugo#131]
Right now, in the following partials:

- about.html
- contact.html
- portfolio.html
- pricing.html
- team.html

section titles are rendered as follows:

```html
<h2>{{ with .title }} {{ index (split . " ") 0 | safeHTML }} {{ end }}<span class="color">
	{{ with .title }} {{ index (split . " ") 1 | safeHTML }} {{ end }}</span></h2>
```

which means that the section titles get truncated to the first two words.

I propose to modify the code as follows, in order to handle section titles longer than two words:

```html
<h2>{{ with .title }} {{ index (split . " ") 0 | safeHTML }} {{ end }}<span class="color">
	{{ with .title }} {{ after (len (index (split . " ") 0)) . | safeHTML }} {{ end }}</span></h2>
```

**Comment by developer-evan** [comment]
Hey there, thanks for your concern, we appreciate your contribution. I changed it and made an update.

**Comment by gdsantoro** [comment]
Thanks for the quick update.

I've just had a look at the latest commit and it looks like there are still some changes to be made, though.

In fact, a quick search for the text `index (split . " ") 1` shows that there are still occurrences to update in the following files:

- layouts/_default/list.html
- layouts/author/single.html
- layouts/partials/about.html
- layouts/partials/blog.html

**Comment by developer-evan** [comment]
Hey there, it will be great if you make a pull request. or i will think about it on the next update. thanks
