### ISSUE TITLE
Site doesn't work in domains

### ISSUE THREAD

**Issue by Radamant24** [themefisher/meghna-hugo#133]
Hello,

I pointed my domain to the site hosted in my netlify account but all requests fail, including the CSS ones.

I discovered that it will only work with the URL that is defined in `config.toml` as `baseURL`

This is weird because I only see this variable being used in anchor tags like this:

![image](https://user-images.githubusercontent.com/25852765/90993044-adf4c000-e589-11ea-8eaa-f0711b8f950a.png)

This breaks a common usecase that is having `https://www.examplesite.com` and `https://examplesite.com` domains to access the site.

Regards

**Comment by lagouille** [comment]
what you say makes no sense to me.

baseURL **should** be the url you use. this is the way hugo works.

can you explicit what you're trying to achieve ??

**Comment by divinerites** [comment]
what you say makes no sense to me.

baseURL should be the url you use. this is the way hugo works.

can you explicit what you're trying to achieve ??

**Comment by Radamant24** [comment]
Hello,

I have a domain, let's call it `https://exampleSite.com`, I can put it as baseURL and it works.
But all modern web pages support the same domain with `www` as a subdomain, like this: `https://www.exampleSite.com`.

This is a very common usecase, but I can't get it to work because all resource requests are being made to the baseURL, and requests from  `https://www.exampleSite.com` are blocked and the page won't load any css or js if the baseURL is  `https://exampleSite.com`

Is there a way to add multiple urls or stop the requests from using that baseURL instead of the current one?

Adding a CORS whitelist could work but I added a `_headers` file and a field to `netlify.toml` and it didn't work, do you know how to enable CORS?


Thanks

**Comment by divinerites** [comment]
This is  has nothing to do with Hugo.

- Hugo is configured for 1 domain in base url

- management of your dns and domain names is not Hugo responsibility.

- but as benefit because you use netlify you can generate '_redirect' files
directly from Hugo. See documentation.

But you also can do that from netlify.

**Comment by divinerites** [comment]
Cors is overcomplicating a simple dns management from netlify

**Comment by Radamant24** [comment]
The issue was solved by creating a 301 redirect in `netlify.toml`
