### ISSUE TITLE
Change from dark to light version of meghna-hugo theme

### ISSUE THREAD

**Issue by bigo229** [themefisher/meghna-hugo#134]
Hi, what do i have to edit in style.css to change from dark to a light version of meghna-hugo theme?. Also how do use custom.css?

**Comment by developer-evan** [comment]
Hey, for doing this, you need to change body color, font-color, and some box or shape color. You need to find all the color and replace them with a new color. It will tough for you if you don't know how to customize css. 

You can contact us for any kind of customization at themefisher@gmail.com (paid)

**Comment by bigo229** [comment]
Thanks Evan, I will change the css as you have suggested

Many Thanks

**Comment by bigo229** [comment]
How do i add a new page tomeghna-hugo theme?

**Comment by developer-evan** [comment]
hey there, you can follow this doc to do this https://docs.gethugothemes.com/guide/#maintain-page

**Comment by Chevindu** [comment]
@bigo229 you might want to make use of [CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) for this one. Just in case you'd like to easily switch between darker and lighter color schemes.
