### ISSUE TITLE
Blog post select options "read more" and "view all posts" just hangs.

### ISSUE THREAD

**Issue by escortcvh** [themefisher/meghna-hugo#136]
When selecting the "Read More" or "View all posts" options on Netlify,  the preloader just hangs on a blank page. These options work perfectly on localhost. Does this possibly have anything to do with google maps not installing correctly?
I have downloaded the theme 3 times and get the same error message regarding maps not being able to open pages.
Help would be appreciated.

**Comment by developer-evan** [comment]
Hey @escortcvh 

As you told, I host the theme on netlify, and didn't find any issue like that. here is the live url https://elastic-wilson-a9ce3a.netlify.app/

**Comment by escortcvh** [comment]
Hi @developer-evan 

Thank you for your reply and you're absolutely right, the live url sent works perfectly.
I read on the netlify forum that hugo themes sometimes don't play nice with neflify unless it's downloaded using git submodules clone, I downloaded .zip files before so will try this method and let you know the results.
Hopefully it works, as I really like your theme.

**Comment by developer-evan** [comment]
Hey @escortcvh 

Nice to hear from you that works, It will be great if you give this theme a star.
