### ISSUE TITLE
How does the contact form work?

### ISSUE THREAD

**Issue by bsamadi** [themefisher/meghna-hugo#14]
When I click on the Submit button in the contact form, I receive a 404 error from GitLab. Where is the send_email.php supposed to be?

**Comment by zeigerpuppy** [comment]
the `send_mail.php` doesn't appear to be included with the theme.  I am trying to work this out too, see here: https://github.com/themefisher/meghna-hugo/issues/15

**Comment by mehedi-sharif** [comment]
@bsamadi , The send mail is not configure properly here . I would suggest you to use https://formspree.io . Its has a free version and easy to use . 
Thanks

**Comment by Magica-Chen** [comment]
@bsamadi https://formspree.io is really cool.
