### ISSUE TITLE
WebP / Safari 14.0

### ISSUE THREAD

**Issue by ckildau** [themefisher/meghna-hugo#143]
Following your install instructions of:
$ git clone git@github.com:themefisher/meghna-hugo.git
$ cd meghna-hugo/exampleSite/
$ hugo server --themesDir ../..

Fails to display background images for me in Safari 14.0 (not sure about older versions).
Chrome, Firefox do show them correctly.

Your demo site at http://demo.themefisher.com/meghna-hugo/ does show them correctly, tough.

Is this a known issue?

**Comment by developer-evan** [comment]
Hey @ckildau 

I don't have a mac at this time, can you please give me a live URL by hosting it on netlify?

**Comment by ckildau** [comment]
I am not familiar with netlify, tough I have just uploaded the result of "hugo --themesDir ../.." to https://files.unixhosts.org/meghna-test/ for public access. Let me know if I can help you out with any debug output from Safari.

**Comment by divinerites** [comment]
This is not a Hugo/Meghna problem.
This is your web server not responding correctly for Safari (or the other way around) I think.
The code is correct. The files are here. But the server doesn't behave well for the WebP image on Safari.

See screenshot.
![Uploading Capture d’écran 2020-11-07 à 12.01.57.png…]()

**Comment by divinerites** [comment]
Ahhhh ... 

May be there are bad/faulty WebP images with Safari, because some WebP are loading correctly.

Can you try to exchange the "bad" ones for a "good" one in your Hugo .Params and see if it works ?

<img width="1013" alt="Capture d’écran 2020-11-07 à 12 08 41" src="https://user-images.githubusercontent.com/32342823/98439436-26cbd880-20f2-11eb-9832-f4ca19578dec.png">

**Comment by divinerites** [comment]
I confirm that Safari (14 in my case) doesn't behave properly but the fallback to .jpg should work.

**Comment by ckildau** [comment]
Just for clarification: .jpg fallback does not work for me in Safari 14.0. Changing from my webservers to hugo internal server shows the same issue as well.

Is there any additional information I can provide?

FYI this does work in latest Safari for iOS for me.

**Comment by divinerites** [comment]
This my code working for the fallback on Safari 14.0 on Mojave.

Do you have some différences ? (I modified a lot the original code, so not sur if it is the original one)

```
<section class="hero-area" style='background-image: url("{{ .bg_image_webp | absURL }}")' id="banner">
	<!-- this image is for trigger this section fallback background image -->
	<img class = "lozad" style="display: none;" onerror="this.onerror=null;this.parentElement.style.backgroundImage= 'url({{ .bg_image | relURL  }})'" src="{{ .bg_image_webp | absURL }}" alt="background image" />
```

**Comment by ckildau** [comment]
Mine looks like https://github.com/themefisher/meghna-hugo/blob/master/layouts/partials/banner.html:
<section class="hero-area" style='background-image: url("{{ .bg_image_webp | absURL }}")'>
	
	<img class="lozad d-none" data-src="{{ .bg_image_webp | absURL }}" onerror="this.onerror=null;this.parentElement.style.backgroundImage= 'url({{ .bg_image | absURL }})'"/>


So, slightly different from yours.

**Comment by ckildau** [comment]
Debugging this further... src instead of data-src does the trick for me: 

`<img class="lozad d-none" src="{{ .bg_image_webp | absURL }}" onerror="this.onerror=null;this.parentElement.style.backgroundImage= 'url({{ .bg_image | absURL }})'"/>`
instead of 
`<img class="lozad d-none" data-src="{{ .bg_image_webp | absURL }}" onerror="this.onerror=null;this.parentElement.style.backgroundImage= 'url({{ .bg_image | absURL }})'"/>`

**Comment by developer-evan** [comment]
@ckildau 

I have also made an update for fixing this bug. If you want, you can download the latest code. Thanks for being with themefisher.
