### ISSUE TITLE
A second team section

### ISSUE THREAD

**Issue by DACN** [themefisher/meghna-hugo#144]
I want to add a second team section (compare issue #47 on pricing).
* I have duplicated: team.yml and called it team2.yml
* I have duplicated: team.html and called it team2.html

But the instructions in #47 say that in pricing2.html ".Site.Data.pricing with .Site.Data.pricing2". 
In this case I cannot see anything called .Site.Data.team
But there are various other references to team, which I have tried to change, such as

{{ if $data.team2.team2.enable }}
{{ with $data.team2.team2 }}
{{"" | safeHTML}}
<section id="team2" class="section">

But so far, no success

**Comment by DACN** [comment]
Aha - making progress. In layouts\index.html I have added a line

{{ partial "team2.html" . }}

**Comment by developer-evan** [comment]
Mention me, if you need any more help...

**Comment by DACN** [comment]
Closing this now; as am happy as these changes above

{{ if $data.team2.team2.enable }}
{{ with $data.team2.team2 }}
{{"" | safeHTML}}

and adding in 

{{ partial "team2.html" . }}   to layouts\index.html

seem to work fine

**Comment by DACN** [comment]
Thanks

David
