### ISSUE TITLE
returning an AJAX result from PHP to the contact form.

### ISSUE THREAD

**Issue by zeigerpuppy** [themefisher/meghna-hugo#15]
I have coded up some PHP to get the contact form to work, however, the javascript doesn't seem to grab the returned value from PHP.  I am not sure if I am using the right parsing of the returned value.  I am happy for the PHP code to be included with the theme.

The PHP sends an email properly with the values from the form, but then it displays a blank page with `sent`.  
I have tried a few different things using `json_encode()`, echoing and using `return`, but nothing seems to return the result that the javascript is waiting for to trigger the `#mail-success` action.

Here are the additions/modifications I made to get the sending working:

------------------

1. slight modification to `static/js/script.js (line 150-2) to get some debugging:

```js
			$.post("php/mailer.php", $("#contact-form").serialize(), function (result) {
				//log the result from the script
				console.log(result);
```

I am not getting any console output for the `console.log(result);`.  There are no server-side PHP errors.

2. slight change from line 28 of `layouts/partials/contact.html` to call correct script and for the spam honeypot (which works by tricking spam scripts to enter the `email` field but not the `email_real` field (it's surprisingly effective at stopping spam!):

```html
            {{"<!-- Contact Form -->" | safeHTML}}
            <div class="contact-form col-md-6 wow fadeInUp" data-wow-duration="500ms" data-wow-delay="300ms">
                <form id="contact-form" method="post" action="php/mailer.php" role="form">

                    <div class="form-group">
                        <input type="text" placeholder="Your Name" class="form-control" name="name" id="name">
                    </div>

                    <div class="form-group">
                        <input type="text" name="email" style="display: none;">
                        <input type="text" placeholder="Your Email" class="form-control" name="email_real" id="email">
                    </div>
```

3. added `phpmailer` folder to `static/php/`, includes `Exception.php`, `PHPMailer.php`, `SMTP.php`.  

4. addition of `static/php/mailer.php (emails/passwords redacted):
```php
<?php

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'phpmailer/Exception.php';
require 'phpmailer/PHPMailer.php';
require 'phpmailer/SMTP.php';

  //$mail->SMTPDebug  = 2;

  // this should catch a lot of spam bots
  $honeypot = trim($_POST["email"]);

  if(!empty($honeypot)) {
    echo "BAD ROBOT!";
    exit;
  }

  $msg = '';
  //Don't run this unless we're handling a form submission
  if (array_key_exists('email', $_POST)) {
    date_default_timezone_set('Etc/UTC');
    $mail = new PHPMailer;
    //Tell PHPMailer to use SMTP - requires a local mail server
    //Faster and safer than using mail()
    $mail->isSMTP();                                      // Set mailer to use SMTP
    $mail->Host = 'smtp.server.net';                    // Specify main and backup SMTP servers
    $mail->SMTPAuth = true;                               // Enable SMTP authentication
    $mail->Username = 'mailer@server.net';              // SMTP username
    $mail->Password = 'mailerPASSWord';                     // SMTP password
    $mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
    $mail->Port = 25;                                     // TCP port to connect to
    //Use a fixed address in your own domain as the from address
    //**DO NOT** use the submitter's address here as it will be forgery
    //and will cause your messages to fail SPF checks
    $mail->setFrom('contacts@email.address', 'Website Contact Form');
    //Send the message to yourself, or whoever should receive contact for submissions

    $mail->addAddress('sender@server.net', 'Your Name');
    //Put the submitter's address in a reply-to header
    //This will fail if the address provided is invalid,
    //in which case we should ignore the whole request
    if ($mail->addReplyTo($_POST['email_real'], $_POST['name'])) {
        $mail->Subject = 'PHPMailer contact form';
        //Keep it simple - don't use HTML
        $mail->isHTML(false);
        //Build a simple message body
        $mail->Body = <<<EOT
Email: {$_POST['email_real']}
Name: {$_POST['name']}
Message: {$_POST['message']}
EOT;
        //Send the message, check for errors
        if (!$mail->send()) {
            //The reason for failing to send will be in $mail->ErrorInfo
            //but you shouldn't display errors to users - process the error, log it on your server.
            $msg = 'Sorry, something went wrong. Please try again later.';
        } else {
            $msg = 'sent';
        }
    } else {
        $msg = 'Invalid email address, message ignored.';
    }

  echo $msg;
  return $msg;
  }

?>
```

**Comment by mehedi-sharif** [comment]
If your codes are working please make a pull request . So that I can merge with this repository . 
Thanks

**Comment by zeigerpuppy** [comment]
@mehedi-sharif do you have the original PHP files referred to in the theme? they'd really help to get this going properly!

**Comment by zeigerpuppy** [comment]
please re-open this issue as the PHP contact form is currently broken

**Comment by zeigerpuppy** [comment]
We can't use third party emailers for privacy.  The mailer works, it's just the javascript callbacks that are not working (and would also not work with a third party site).  Do you have access to the original sendmail.php file that is referred to in the theme?  With that we could definitely get it going.  I guess these theme files came from a theme that was developed for another engine apart from hugo, the original code would really help.

**Comment by mehedi-sharif** [comment]
Meghna hugo is ported from https://themefisher.com/products/meghna-free-responsive-one-page-business-template/ this template . The original email php file is included in the pro version of meghna. I suggest you to purchase that one . 
Thanks

**Comment by baianomauricio** [comment]
Has anyone tried the fix that zeigerpuppy provided here? If so, is it working?

**Comment by diegogangl** [comment]
In case someone stumbles across this issue, you need to return false in the jquery post callback so it stops the redirection.
From the example at the top:
```js
			$.post("php/mailer.php", $("#contact-form").serialize(), function (result) {
				//log the result from the script
				console.log(result);
                                return false;
                         });
```
