### ISSUE TITLE
Make banner image responsive

### ISSUE THREAD

**Issue by eddbmxdude** [themefisher/meghna-hugo#151]
Hi,

I'm brand new to static site generators and Hugo. I love the theme, I'm using it to build my new website.

I've added an image to my top banner which looks great on desktop but it doesn't resize for mobiles. Is there a way to make it responive?

Thanks,
Edd

**Comment by somratpro** [comment]
Hello @eddbmxdude 

Thanks for choosing our template, the banner is a background image, and it's cover for all devices, so you need to know some css to responsive it on a mobile device, and you can set different proportions for different devices. you can read some articles like this one https://www.webfx.com/blog/web-design/responsive-background-image/ to set your background image as you want. 

And also a star to the repository would be really appreciated, thank you.
