### ISSUE TITLE
The mobile navigation bar jumps abnormally

### ISSUE THREAD

**Issue by shenweiyan** [themefisher/meghna-hugo#154]
Click the navigation bar on the mobile terminal, the height of the page jump is inconsistent.

**Comment by somratpro** [comment]
Hello @shenweiyan 

Can you share a short video?

**Comment by shenweiyan** [comment]
I make a test for my remote server with:
```
hugo server --baseUrl=135.181.12.62 --bind=0.0.0.0 --themesDir ../..
```

It seems someting wrong with clicking the navigation bar on the mobile terminal, but when I deploy it to github pages all goes well.


https://user-images.githubusercontent.com/26101369/108807221-c7c99b00-75de-11eb-85cd-f2b6bb0c27ab.mp4

**Comment by shenweiyan** [comment]
I make a test on my remote server with:
```
hugo server --baseUrl=135.181.23.59 --bind=0.0.0.0 --themesDir ../..
```
 It seems something wrong whit clicking the navigation bar on the mobile terminal, but when I deploy it to github pages all goes well.

https://user-images.githubusercontent.com/26101369/108810100-4fb2a380-75e5-11eb-9605-383223e038bf.mp4

**Comment by somratpro** [comment]
Hello @shenweiyan 

Thank you. we just did a quick fix, but it's not the way. we will update it later when we are free. you can use the quick fix by downloading the latest version.
