### ISSUE TITLE
i18n not work for clicking the navigation bar items

### ISSUE THREAD

**Issue by shenweiyan** [themefisher/meghna-hugo#155]
I18n in the navigation bar will automatically switch to English. It seems there is something wrong with Fr when clicking the navigation bar items, which will automatically switch to En.

https://user-images.githubusercontent.com/26101369/109246909-0600cd80-781e-11eb-8fcc-d202c3bbe211.mp4

**Comment by somratpro** [comment]
Helllo @shenweiyan 

Thanks for your concern. It was a bug, and we fix it. now you can download the latest code and enjoy...!

Also if you like this template, a star to the repository would be amazing.

**Comment by shenweiyan** [comment]
Thank you very much. meghna-hugo is a great theme and I have stared and forked it.

**Comment by shenweiyan** [comment]
> Helllo @shenweiyan
> 
> Thanks for your concern. It was a bug, and we fix it. now you can download the latest code and enjoy...!
> 
> Also if you like this template, a star to the repository would be amazing.

It seems it is not work for the latest code.

**Comment by somratpro** [comment]
I check on my localhost, and it was working fine. can you explain how it is not working?

**Comment by shenweiyan** [comment]
The problem is the same as the previous screenshot, I change the language to Fr, but when I clicking the navigation bar items, it will automatically switch to En. This is my site on the remote server：http://135.181.12.62:1313/

**Comment by somratpro** [comment]
This should not happen, please download the code and run hugo server on it separately, don't mix it with your existing one. I checked it again and it works fine, no issue at all.

**Comment by shenweiyan** [comment]
> This should not happen, please download the code and run hugo server on it separately, don't mix it with your existing one. I checked it again and it works fine, no issue at all.

ok, It works fine for me now. Thank you very much for your patient help.
