### ISSUE TITLE
Google Analytics, Tag manager

### ISSUE THREAD

**Issue by Oxko** [themefisher/meghna-hugo#158]
Hi Team, 
I wonder can you advise where to add in the template the google analytics and tag manager html codes? 
Also per google setup i need to add the html codes to each section in the site, although there is one single field already setup in Hugo to add the analytics ID only, and that is in the config.toml. 
But I cannot figure out where to add the analytics and tag manager's html codes in the template?.

**Comment by somratpro** [comment]
Hello @Oxko 

You can add Analytics ID in config.toml file, no need to add the script, and Tag manager script paste in `layouts>partials>head.html`

**Comment by Oxko** [comment]
Thanks a lot.
