### ISSUE TITLE
I lost my localhost

### ISSUE THREAD

**Issue by Oxko** [themefisher/meghna-hugo#159]
Hi Team, Could you please help me check maybe? I am struggling to find the issue why my site stopped running on local host. 
I have in the end deleted everything from PC and pulled my site from the repository to run it but it just doesnt load on local host. I have compared each file also with the master hugo theme files, without any luck. 

The main theme does work, but when i want to run my own site what worked before, it s blank. 

Could you advise what could be the issue, what to check? It started almost right after https configuration was done, then my VSC closed down due to some update and since then there is just no local host. I d think there is no connection, but still, this is what happened before it got totally blank.. :( 

So much thanks!

**Comment by somratpro** [comment]
Hello @Oxko 

I think you lost the exampleSite. I am sending you a video, it might help you https://youtu.be/dyZcRRWiuuw

**Comment by somratpro** [comment]
Can you share your repository?

**Comment by Oxko** [comment]
@somratpro 

https://github.com/Oxko/meghna-hugo.git
https://github.com/Oxko/meghna-hugo

Thank you so much if you can look into it.

**Comment by somratpro** [comment]
Change your `defaultContentLanguage = "Hu"` to `defaultContentLanguage = "hu"`, then run hugo server.

**Comment by Oxko** [comment]
@somratpro, I cant believe it was this simple, thanks so much! :) I sweat blood trying to figure out the issue :)
