### ISSUE TITLE
Hugo Submodules Issue

### ISSUE THREAD

**Issue by romaindivozzo** [themefisher/meghna-hugo#165]
Hello, I've been using Hugo templates for a while now, I kind of always find ways to make things work but for some reasons I cannot make this the meghna template work at all. It did work for a while on my local server, but when I tried to get a static webpage from gitlab I never succeeded. 

Is there anything special about this template I should know of that is different from other Hugo templates ? I just tried again with beautiful hugo and gitlab and it works perfectly.

I can give more details but I am wondering if someone is having issues to host this template on gitlab ?

Thanks !

**Comment by divinerites** [comment]
I do not deploy on GitLab but on Netlify.
But I never ever had issues with themefisher theme.

I suspect that your deploy workflow has some issue somehow; depending on how you setup your repository.

**Comment by romaindivozzo** [comment]
@divinerites Thank you for your answer. 

The message I get from my terminal when I try to deploy is : "Module "meghna-hugo" not found; either add it as a Hugo Module or store it in "/Users".: module does not exist".

It might be because I just don't know enough about submodules. But I can't find a work-around for this.

**Comment by divinerites** [comment]
As is, the actual Meghna theme is NOT a hugo module.

https://gohugo.io/hugo-modules/

**Comment by urmel1960** [comment]
I do have the same problem. 
I followed the description her https://docs.gethugothemes.com/meghna/installation/
and run into 
`Error: module "meghna-hugo" not found; either add it as a Hugo Module or store it in "/".: module does not exist`

**Comment by somratpro** [comment]
Hello @urmel1960 

Please follow this doc https://docs.gethugothemes.com/guide/#local-development
