### ISSUE TITLE
Latest Posts header not showing

### ISSUE THREAD

**Issue by zach-andrews** [themefisher/meghna-hugo#169]
When working with this theme I added 3 test blog posts. I can see those posts but the header "Latest Posts" and the read more buttons are empty. Did I miss a configuration setting somewhere? 
![blog](https://user-images.githubusercontent.com/45575092/122484900-eb03c600-cf92-11eb-9384-b477e9fb9b21.png)

**Comment by somratpro** [comment]
Hello @zach-andrews 

That is happening because this theme is a multilingual theme, and those stings are coming from `i18n translations`.  Please check `i18n` folder for those missing text.

**Comment by zach-andrews** [comment]
That fixed it! Thank you so much!
