### ISSUE TITLE
Outdated documentation: Drop Down Menu

### ISSUE THREAD

**Issue by ChsRmb** [themefisher/meghna-hugo#176]
Hey,
I've tried to use the drop down menu but it doesn't work.

So I looked into the issues, maybe somebody else had the same problem. 
I've found the issue #94, but the current documentation says that drop down menus are possible.

Link to the outdated documentation: https://docs.gethugothemes.com/meghna/navigation/

**Comment by tfsomrat** [comment]
Hello @ChsRmb 

Yes, it's possible now. please download the latest code. Also if you like this template, please consider giving it a star. thank you
