### ISSUE TITLE
Share button dont show the url (facebook , twitter ,and more )

### ISSUE THREAD

**Issue by thesky03** [themefisher/meghna-hugo#177]
I tired search the config file of url share button its always open and share /blog/how-to-setup-hugo/ how do i fix this ? 
I already change the  config.toml  base url but nothing happened

**Comment by tfsomrat** [comment]
Hello @thesky03 

You are using an env_variable for baseURL when using netlify. so you need to remove this line `HUGO_BASEURL = "/"` from netlify.toml at line 8.

**Comment by thesky03** [comment]
Thanks you... Its workss!

**Comment by tfsomrat** [comment]
Good to know it works. It will be great if you give a star to the repository. thanks
