### ISSUE TITLE
Struggling with Meghna

### ISSUE THREAD

**Issue by romaindivozzo** [themefisher/meghna-hugo#179]
Hi,

I've been fighting with the Meghna-hugo theme (a lot...and...too much). It always works locally but never works when I deploy it on Gitlab...css is always broken or the theme is not recognized and should be added as a submodule (which I have done but the css would never update on the static-pages after this). 

I've searched every forum, read every discussions, I am still stuck (not a web dev though but I usually end-up making things work).

I want to use it without using Netlify or Forestree. Not interested by the CMS part.

Would you know where I could check the directory of a working static page with Meghna as a theme and that is working without netlify and forestree ?

That would help a lot,

Thanks !

**Comment by tfsomrat** [comment]
Hello @romaindivozzo 

Thanks for choosing our theme. You need to update your baseURL in `config.toml` file. If your site domain is `https://example.gitlab.io`, then use this URL in your baseURL field. then deploy it again. it will work.

**Comment by romaindivozzo** [comment]
Thanks a lot @tfsomrat, it worked when I added the new BaseURL as you said. Changes I make in the config.toml file that's inside the root directory work.

Now, when I want to modify the style.css from the meghna-hugo submodule (it is under themes in the root directory), through the Terminal, Github keeps asking me for some credentials. And more problems after that.

For now I am just changing the background color (to #63003c). When I put my webpage in full screen I can see the #63003c background color for a seconde but it doesn't show on the page. It is hiding somewhere behind :

<img width="2560" alt="Screenshot 2021-11-30 at 11 05 58" src="https://user-images.githubusercontent.com/5367061/144027705-9d968715-f2d4-412b-81a2-571053e0c687.png">

I really wish I could customize this website.

Tips and tricks welcome !

**Comment by tfsomrat** [comment]
Hey @romaindivozzo 

That's great news. I actually don't know why this is happening, until I see the code. We can give support for theme customization [paid]. If you want, you can contact us at mehedi@themefisher.com. thank you
