### ISSUE TITLE
How to change the icons?

### ISSUE THREAD

**Issue by Zephir1425** [themefisher/meghna-hugo#18]
Hi, I'm trying to change some of the icons (about us 1 and 2 especially) but I cannot find where you import them from (and thus get a list of alternatives). I would be grateful if you could give me some pointers. Thanks lot.

**Comment by mehedi-sharif** [comment]
Hello @Zephir1425  , 
In meghna we use our own icon font . 
https://github.com/themefisher/themefisher-font . 
Please download this file and open demo.html file . You will get a bounce of icons list. 
Thanks

**Comment by Zephir1425** [comment]
Great, thanks a lot

**Comment by BorisBass** [comment]
hi,
how can i change the icons (some of them)
thank you

**Comment by StayTips** [comment]
link is unreachable
