### ISSUE TITLE
Drop Down Menu Not Working

### ISSUE THREAD

**Issue by dradux** [themefisher/meghna-hugo#182]
I am running the latest version of the theme (released 2021-09-01) on hugo `Hugo Static Site Generator v0.76.5-60F0725B/extended linux/amd64 BuildDate: 2020-10-14T15:25:14Z`. 

The drop down menu is not working. I get a menu item (tools) with the drop down arrow showing but nothing shows in the menu when you click or hover.
![2022-01-01_1312 19_1040x740_scrot](https://user-images.githubusercontent.com/4999736/147857356-d5c61f98-afc0-4bf9-8b1e-9b1ceacc848f.png)

If I look at the source code of the page in the debugger I can see the menu parent and child are present:
```
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        tools
    </a>
     <div class="dropdown-menu">
        <a class="dropdown-item" href="/contact">trax</a>
     </div>
</li>
```

My menu in `config.toml` is defined as follows:

```
[[Languages.en.menu.main]]
name = "tools"
hasChildren = true
weight = 10
	[[Languages.en.menu.main]]
	parent = "tools"
	name = "trax"
	url = "contact"
```

**Comment by tfsomrat** [comment]
Hello @dradux 

I checked this theme in my localhost, and it works fine. So I added a demo dropdown and made an update. you can check the latest code running into your localhost. Also if it doesn't work, try to clear your browser cache, or open an incognito tab. thanks

**Comment by dradux** [comment]
thanks @tfsomrat , turns out my issue was I had disabled bootstap.min.js as I didn't need it before and I forgot to recheck after adding the dropdown in. I really appreciate the quick reply and your adding the dropdown to the exampleSite. 

For those who may later find this, I disabled the following in `config.toml` which kept the dropdown from working:

```
#[[params.plugins.js]]
#link = "plugins/bootstrap/bootstrap.min.js"
```
