### ISSUE TITLE
Error importing to Forestry.io: Hugo config file not found

### ISSUE THREAD

**Issue by kaz875** [themefisher/meghna-hugo#184]
When trying to import to Forestry.io I keep running into this error. Should we add an empty file instead?

**Comment by tfsomrat** [comment]
Hello @kaz875 
Please follow this video tutorial https://youtu.be/ResipmZmpDU

**Comment by tfsomrat** [comment]
Hey @kaz875 
Hope your problem has been resolved, I am closing this issue, if you have any queries, you can re-open this issue or create a new one. thanks
