### ISSUE TITLE
Images not loaded correctly, only works after switching languages

### ISSUE THREAD

**Issue by cosimameyer** [themefisher/meghna-hugo#186]
Hi,

I hope this is the right place to ask. I am using your theme Meghna Hugo and love it! 
I deployed it with Netlify for a bit but went for a (manual) FTP-Deploy pipeline with another hosting service to comply with the GDPR regulations. Since deploying it with the pipeline, I am having trouble loading the images (the logo, fontawesome, and some other images on the landing page are not loaded correctly and only displayed after switching to the other language (German; English - it doesn't matter which one is the default)). I realized that this only seems to happen when I go for the base URL (https://www.ram-ev.de/) but not when I actively access a language selection first (for instance https://www.ram-ev.de/de/). I am clueless why this should be the case and was hoping that you had an idea. 

Here's the [Github repo](https://github.com/cosimameyer/ram-homepage-clean).

Thanks so much!

**Comment by tfsomrat** [comment]
Hello @cosimameyer 

Thanks for choosing our theme. I visited your both URL, and every image is loaded correctly in both languages. Maybe I didn't understand what is your actual issue. can you give some Screenshots, so I can understand properly?

**Comment by cosimameyer** [comment]
Hi @tfsomrat,

Thanks for getting back to me so quickly. I just accessed the website in the phone and still have the same issues (see screenshots). I tried it both with the mobile and on the computer (using Safari, Firefox, Google Chrome) - observing this behavior every time. 

In the testimonial carousel, I would expect to have only one person present (works locally and also after refreshing) and it is missing the images: 
![79236D6C-39DC-4E17-A7C6-3E4065306C79](https://user-images.githubusercontent.com/7782895/159629748-76c80df6-cefe-41c7-b4b9-565d98f000b3.jpeg)

For the fun facts counter, the numbers are not starting to count:
![6498ECB3-A99A-4114-9703-BD26F1B38F6F](https://user-images.githubusercontent.com/7782895/159629752-113875e9-3bb8-4f63-92fa-686f9798f252.jpeg)

The logo is missing at the top of the page:
![893C2AF2-145B-4EB0-BE59-5BB48568C8F0](https://user-images.githubusercontent.com/7782895/159629753-32992249-7678-45a2-b7d9-c6d2f3d3e4cd.jpeg)

Thanks so much for your support!

**Comment by tfsomrat** [comment]
This is what I can see
![image](https://user-images.githubusercontent.com/58769763/159834140-2e66c0d4-dfd8-48c9-958b-3c2eb34b703c.png)

**Comment by tfsomrat** [comment]
Sure, I am using Mac-OS and I have tested every browser, and it works everywhere.

**Comment by cosimameyer** [comment]
Thanks for the feedback! I asked a few more people to check it independently and they all experience the same issue. I thought about quick fixes and (as far as I can see it) one way would be to implement a redirect that actively directs the user to a language selection once entering the landing page (https://www.ram-ev.de/ > https://www.ram-ev.de/de/). I am aware that there are disadvantages to this solution but it could solve the issue. What would be your recommendation to implement a redirect in this theme?

**Comment by tfsomrat** [comment]
I'm afraid, I don't know the actual way to do that. hope you find out a way for that. thank you

**Comment by cosimameyer** [comment]
Thanks so much - we solved the problem by tweaking the .htaccess file and adjusting some internal settings at our hosting service 😊 

(I'll close the issue since we found a workaround)
