### ISSUE TITLE
Load more button in Portfolio

### ISSUE THREAD

**Issue by aiBR3** [themefisher/meghna-hugo#187]
It would be possible to:

* set a maximum number of items to show in the Portfolio (useful for those who like me have a very large portfolio, which lengthens considerably the height of the page)
* add a *load more* button to load all the remaining elements (and basically show the page as in the current version of the theme)

**Comment by tfsomrat** [comment]
Hello @aiBR3 

Yes, it's possible to do that. you can get the idea from here https://gohugo.io/functions/first/

and if you still need professional help, then we are available for hire, you can contact us at mehedi@themefisher.com
