### ISSUE TITLE
How do I enable SEO?

### ISSUE THREAD

**Issue by jloveland** [themefisher/meghna-hugo#19]
I put the following in `config.toml`:
```
enableRobotsTXT = true
canonifyURLs = true
```
What else should I do?

**Comment by mehedi-sharif** [comment]
@jloveland  , 

> ```
> enableRobotsTXT = true
> canonifyURLs = true
> ```
By enabaling this parameters you are actually giving search engine some data . I think yes your website is not seo enabled . To make website more seo friend you have to create meta data , meta description , title etc .
