### ISSUE TITLE
Navigation "hamburger" menu in mobile scroll issues

### ISSUE THREAD

**Issue by oscarmrom** [themefisher/meghna-hugo#22]
When using the navigation menu to scroll to *About Us*, *Services*, or *Portfolio* / *Our Works* it scrolls to the sections but cuts off the top of the words from scrolling a bit too far down. Examples below:

<img width="583" alt="image" src="https://user-images.githubusercontent.com/26697231/52252399-46f0b700-28d0-11e9-8819-90ef8316455b.png">

<img width="589" alt="image" src="https://user-images.githubusercontent.com/26697231/52252409-5112b580-28d0-11e9-83ec-8bd01b4b429d.png">

Also, because of the images in *Our Works* collapsing and expanding, the scroll via the navigation menu to *Team* does not scroll appropriately. It does go that section when the menu is open but gets pushed down as the images expand when closing the menu. This affects all sections below the *Portfolio* / *Our Works* section. **After testing on my android, it appears this happens in the Firefox dev tools mobile view and not my phone.** *It appears that the Chrome Dev Tools for mobile doesn't have this issue either.*

Example below:

Menu open:
<img width="567" alt="image" src="https://user-images.githubusercontent.com/26697231/52252571-152c2000-28d1-11e9-8ddd-a9989c1a2140.png">

Menu closed:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/26697231/52252579-1eb58800-28d1-11e9-9aee-463f04ba9bdc.png">

Also, after the navigation menu is opened, clicking outside of it does not close the menu. UX suffers from this. Tapping outside of the navigation menu on the page should close the menu, too.

**Comment by mehedi-sharif** [comment]
Fixed issues , But the last screen is not possible as we used bootstrap here . 
Thanks
