### ISSUE TITLE
how to include tags?

### ISSUE THREAD

**Issue by Zephir1425** [themefisher/meghna-hugo#23]
Hi, I'm trying to include tags. I add something like tags:["tagA"] in frontmatter for a post but nothing is showing up? Would you happen to know why? Thanks a lot.

**Comment by Somrat37** [comment]
hey @Zephir1425 ,
In this template we create a simple blog post, there is no option to add taxonomies, if you want to add taxonomies then you need to customize templates layout, and add option for taxonomies, thanks.
