### ISSUE TITLE
Bootstrap 3 to 4 migration

### ISSUE THREAD

**Issue by loriab** [themefisher/meghna-hugo#24]
This is way too hasty and incomplete (navigation still WIP and in a different file), but here's a pass at Bootstrap 3 to 4 update, in case it helps anyone else: https://github.com/loriab/meghna-hugo/commit/47edbdcd83cccee8e6d7db94d33384aa3607152e .

**Comment by mehedi-sharif** [comment]
Soon we will update meghna in bootstrap 4. Thanks for your concern .

**Comment by loriab** [comment]
Sounds great! Thanks for your theme and continued work on it.

**Comment by mehedi-sharif** [comment]
#25

**Comment by loriab** [comment]
works great, thanks!
