### ISSUE TITLE
multilingual?

### ISSUE THREAD

**Issue by Zephir1425** [themefisher/meghna-hugo#27]
Hi, I love this theme, but I'm struggling to implement a multilingual functionality. I was able to easily do it for the blog posts (using Hugo documentation), however I'm running into errors every time I try to translate the data pages and link them to the layouts. I have also looked at your "navigator" theme for some clues but without success unfortunately. Could you give me some pointers?
Thanks a lot.

**Comment by hawkeye116477** [comment]
Look at my work I done with blog => `https://github.com/themefisher/meghna-hugo/pull/28/files`.
For fist you need to add {`{ $data := index .Site.Data .Site.Language.Lang }}` to layout, then for example instead of `{{ with .Site.Data.blog.heading }}`, just write `{{ with $data.blog.heading }}`. Then you can add translation to `data/langCode/blog.yml`.

**Comment by Zephir1425** [comment]
Thanks. I tried it for the blog section.So it's working for the I18n translation, the button "read all posts" is correctly translated in French. However the "heading" and "headingSpan" is not picked up in either language now. Would you know why?
Also why do you have blog.yml in each language folder (data/en and data/pl) AND also in data root? Can't we just have them in each language folder?

**Comment by hawkeye116477** [comment]
`Also why do you have blog.yml in each language folder (data/en and data/pl) AND also in data root? Can't we just have them in each language folder?`
For common settings, to enable blog section, social sharing for all languages and staticman settings. I just put only translations in each language folder.

**Comment by Zephir1425** [comment]
Actually I already had DefaultContentLanguage="en". But I made 2 errors. 
- In the config file, I had to remove dataDir = data/en (and same thing for fr). 
- Also I was putting {`{ $data := index .Site.Data .Site.Language.Lang }}`above and not below {{"" | safeHTML}} in the layout. 
Thanks for your help

**Comment by burakozturan** [comment]
I am also not able to use the multilingual property. Once I switch from English to additional language, the web site only shows the blogposts but not the other contents like our services, skills, etc. Do you guys any suggestion please?

**Comment by somratpro** [comment]
hey @hawkeye116477, 

Check that you have enabled this section in `exampleSite/data/fr` folder.

**Comment by liguanghe** [comment]
> Thanks. I tried it for the blog section.So it's working for the I18n translation, the button "read all posts" is correctly translated in French. However the "heading" and "headingSpan" is not picked up in either language now. Would you know why? Also why do you have blog.yml in each language folder (data/en and data/pl) AND also in data root? Can't we just have them in each language folder?

---
same problem,Have you solved it?
