### ISSUE TITLE
Layout issue

### ISSUE THREAD

**Issue by DataWookie** [themefisher/meghna-hugo#3]
Hi!

I love the look of this theme on the demo site. I have created a new local hugo site and installed the theme. However, when I run the server the rendered site does not look like the demo. For some reason the formatting is not working out.

I have checked the Javascript console and there are no errors.

Do you have an idea of what could be wrong?

I'm running hugo 0.48 on Ubuntu.

Thank you!

Datawookie.

![screencapture-localhost-1313-2018-11-17-05_00_58](https://user-images.githubusercontent.com/6134409/48655905-693c0c80-ea26-11e8-9977-07696437093e.png)

![screencapture-localhost-1313-2018-11-17-05_01_34](https://user-images.githubusercontent.com/6134409/48655925-c2a43b80-ea26-11e8-8f8e-2902ee44e69c.png)

**Comment by DataWookie** [comment]
I included the image of the VEX site because it seems to have the same problem for me.

**Comment by DataWookie** [comment]
Thanks! Working perfectly now. :)

**Comment by mehedi-sharif** [comment]
what happened ? Is that a issue from our end ?
