### ISSUE TITLE
Contact Form Behavior Changed

### ISSUE THREAD

**Issue by Proziam** [themefisher/meghna-hugo#32]
The behavior of the contact form seems to have changed in recent versions of the theme, not sure how to fix it.

Expected behavior - Submit button says "Mailman is on his way" or similar when a filled out form is input

Actual behavior - new tab opens with "sent" message + the form will send an email regardless of whether the form is filled out or not

I had this working properly with a sendmail.php file before, but I see the new versions have several PHP files and am unsure how it is meant to be set up.

Can see the behaviors in action - https://www.yokotu.com  [using formspree now as a stopgap measure]

**Comment by pzhaonet** [comment]
Hi, @Proziam. I am a new user of this nice theme. I have built a preliminary site with meghna theme, but I do not know how to configure my contact email. In my experience, the contact email can often be configured in config.toml in other Hugo themes, while I cannot find it in meghna-hugo. Could you kindly let me know how to do it? Thanks a lot!

**Comment by hawkeye116477** [comment]
@pzhaonet You can set it on `data/contact.yml`.

**Comment by pzhaonet** [comment]
@hawkeye116477 Got it. Thanks a lot!

**Comment by baianomauricio** [comment]
@pzhaonet - Did the contact form works for you now?

**Comment by pzhaonet** [comment]
@baianomauricio No, it did not work. Maybe I did something wrong. I had no time to do further tests and gave up.

**Comment by ClockWise89** [comment]
All I get is that the sendmail.php does not exist when I submit :/

**Comment by kanekotic** [comment]
+1
I am having the same issue :( . 404 on the form submition. Has anyone found a solution for this?

**Comment by kanekotic** [comment]
So i found out this will never work specially with github pages. So I have done a small PR to add support for `formspree`

**Comment by Oxko** [comment]
Hi, Could you help how to add an attachment upload option in the contact form?

**Comment by somratpro** [comment]
Hey @Oxko

Follow the file uploads instruction from here https://formsubmit.co/documentation

**Comment by Oxko** [comment]
Thank you. Could you please also help how to change the name of the tabs? (about, team and these tabs..)
