### ISSUE TITLE
Menu hamburger not working for multi pages

### ISSUE THREAD

**Issue by Zephir1425** [themefisher/meghna-hugo#33]
Hi, I have basically created new pages corresponding to each section of the landing page. I changed the menu by deleting the # sign in the navigation file in layout in order to link the new pages in the menu which works perfectly. 
However, on mobile, the menu stopped working, when I click on it, it does not work anymore. I have the old menu (before you updated it, I tried the updated version but nothing appears on the screen, not even the hamburger icon). Do I need to update something in the jquery.nav.js?
Here is the corresponding part of the navigation file in layout:
    {{"" | safeHTML}}
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
      {{"" | safeHTML}}

I also added a multi language mode with the following details in the config.toml : 

# Menu

[Languages.en.menu]

    [[Languages.en.menu.nav]]
    name = "Home"
    URL = "/en"
    weight = 1

    [[Languages.en.menu.nav]]
    name = "About Us"
    URL = "/en/about"
    weight = 2
    
    [[Languages.en.menu.nav]]
    name = "Services"
    URL = "/en/services"
    weight = 3

    [[Languages.en.menu.nav]]
    name = "Experience"
    URL = "/en/portfolio"
    weight = 4

    [[Languages.en.menu.nav]]
    name = "Profile"
    URL = "/en/team"
    weight = 5

    [[Languages.en.menu.nav]]
    name = "Blog"
    URL = "/en/blog"
    weight = 6

    [[Languages.en.menu.nav]]
    name = "Contact"
    URL = "/en/contact"
    weight = 7

[Languages.fr.menu]

    [[Languages.fr.menu.nav]]
    name = "Accueil"
    URL = "/fr"
    weight = 1

    [[Languages.fr.menu.nav]]
    name = "A propos"
    URL = "/fr/about"
    weight = 2  
    
    [[Languages.fr.menu.nav]]
    name = "Services"
    URL = "/fr/services"
    weight = 3

    [[Languages.fr.menu.nav]]
    name = "Expérience"
    URL = "/fr/portfolio"
    weight = 4

    [[Languages.fr.menu.nav]]
    name = "Profil"
    URL = "/fr/profile"
    weight = 5

    [[Languages.fr.menu.nav]]
    name = "Blog"
    URL = "/fr/blog"
    weight = 6

    [[Languages.fr.menu.nav]]
    name = "Contact"
    URL = "/fr/contact"
    weight = 7
...

**Comment by hawkeye116477** [comment]
You can remove jquery.nav.js, it isn't needed now, instead of this, now is native smooth scrolling and polyfill for browsers which don't support this. Menu is done by Bootstrap. I checked and it's working fine on my side :smile:.

**Comment by Zephir1425** [comment]
Hi sorry my html did not render on the page. I tried the new menu but I think I would have to upgrade to bootstrap 4 which requires quite a lot of changes and will probably break my website (at least initially). That's why I would like to keep and understand how you built the old one. Here is my code. It seems that you link the hamburger menu with the main menu with the class .navbar-collapse but for some reason, opening the menu does not work.
![hamburgermenu](https://user-images.githubusercontent.com/45423031/53387700-0235d880-39c3-11e9-90ee-78eb5595766e.png)

**Comment by Zephir1425** [comment]
I was able to make it work by adding the following at the top. Not sure why it was working a week ago without it.
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

**Comment by Somrat37** [comment]
@Zephir1425 , please use the latest update. thanks
