### ISSUE TITLE
Font issue - font not working / not loaded

### ISSUE THREAD

**Issue by Freezergeezer** [themefisher/meghna-hugo#35]
Hello. As the title suggests I'm having issues getting the live website to load the font. This is mostly evident because none of the icons are displaying.

This issue doesn't exist during localhost testing.

**Comment by Somrat37** [comment]
Hello, i tried to figure out your submitted issue, but i didn't find this type of font issue. u can check the  [demo](https://themes.gohugo.io/theme/meghna-hugo/) here.
