### ISSUE TITLE
Font not loading

### ISSUE THREAD

**Issue by Freezergeezer** [themefisher/meghna-hugo#37]
The theme-fisher font is not working properly / is not loaded on the live version.None of the icons are displayed. 

For example:
"We're Creative / We're Genius / We're Professional"
each of those has an icon (tools, horse, etc.). During testing the localhost version works fine and they are displayed. However when uploaded live they "break" and the icons do not display (any icon of the same font).

**Comment by mehedi-sharif** [comment]
In the next version we will update the font . 
Thanks

**Comment by Freezergeezer** [comment]
Thanks!

FYI, I have identified the issue: the font only loads if you type "www." in the url. Without it, it doesn't work. Did you identify this as well?

**Comment by hawkeye116477** [comment]
For me it works ok, demo site only have non www version and works ok. That's probably something with your hosting.

**Comment by Freezergeezer** [comment]
> For me it works ok, demo site only has non www version

Could something be wrong with the installation and/or folder structure? I think it' might be more likely a problem there, instead of server hosting.
