### ISSUE TITLE
violation of mixitup 3 license

### ISSUE THREAD

**Issue by OlafHaag** [themefisher/meghna-hugo#38]
Though it's a good use of [MixItUp 3](https://www.kunkalabs.com/mixitup/) in this theme, its redistribution in a free theme seems to be in violation of its licensing terms.

Excerpt from their [licensing site](https://www.kunkalabs.com/mixitup/licenses/):
> Can I distribute MixItUp in a free plugin or theme?
>> No. The legal complexities of distributing software with a proprietary license such as MixItUp in free third-party software make this kind of use extremely difficult. Allowing it would lead to many users bypassing our licensing (unknowingly or otherwise), and as such we no longer permit distribution of MixItUp in free plugins or themes. You may distribute MixItUp in commercial plugins and themes, but a Reseller license is required.
>> If you were distributing MixItUp 2 in any free theme, template or plugin launched before December 10th 2016, you may continue to do so. Use of MixItUp 3 however, or any version of MixItUp in a product released on or after December 10th 2016 must adhere to the policies set out by our current licenses.

**Comment by OlafHaag** [comment]
This issue also applies to your free navigator-hugo theme as far as I can tell.

**Comment by mehedi-sharif** [comment]
@OlafHaag Thanks for your concern . We are going to check this out and soon going to replace it. 
Thanks

**Comment by mehedi-sharif** [comment]
We updated all the scripts. Thanks for noticing this .
