### ISSUE TITLE
simple-slider-post.md missing in example site

### ISSUE THREAD

**Issue by nebukadhezer** [themefisher/meghna-hugo#39]
Hey, 
I was wondering where the simple-slider-post.md is in the example site.
I cannot figure out how to write a "gallery" blog post with the slick slider on top as it is happening in the hosted example site.
Cheers

**Comment by nebukadhezer** [comment]
http://demo.themefisher.com/demos/?theme=meghna
This is happening here..
https://themes.gohugo.io/theme/meghna-hugo/
The go hugo demo is different.
https://github.com/themefisher/meghna-hugo/tree/master/exampleSite/content/blog
Here is neither one content of the demo sites...

**Comment by mehedi-sharif** [comment]
Meghna hugo and meghna html version are totally 2 different theme .

**Comment by nebukadhezer** [comment]
https://github.com/themefisher/meghna-hugo/blob/master/layouts/partials/blog.html
So I would have to make this work in here...
Sorry I just thought the both have the same functionality...
As slick is present in the hugo theme, but it seems it is not being used.
