### ISSUE TITLE
The theme can not view in mobile

### ISSUE THREAD

**Issue by zheddiewen** [themefisher/meghna-hugo#4]
- hugo 0.51 
I find the theme can not view in the mobile.also the demo in official demo.

Thanks for your work!  perfect theme!

**Comment by mehedi-sharif** [comment]
Hello,
In my end the preview works in mobile device . Can you show some screenshots . 
Thanks

**Comment by zheddiewen** [comment]
Thanks!  It's work ,perhaps it's my network problem.
