### ISSUE TITLE
Custom CSS broken

### ISSUE THREAD

**Issue by alexbrt** [themefisher/meghna-hugo#42]
Hi,
It seems like the custom css feature that was implemented in commit 8c527d6ed3709fa536b4fcb75649d8d63a894c3e is now broken. My guess is that it's due to the head.html file which doesn't include the custom stylesheet anymore; however, I'm unable to come up with a fix right now. Mind looking at it?
Thanks!

**Comment by Somrat37** [comment]
Hey there, your problem has been solved.
