### ISSUE TITLE
filterizr display issues

### ISSUE THREAD

**Issue by kathrynloving** [themefisher/meghna-hugo#44]
Thanks for making the meghna-hugo theme, it's great! I had some issues with filterizr, when I changed the main page layout, the portfolio items sometimes ended up on top of each other. (Even if I had made no changes to the portfolio partial.)

At the bottom of [this page](https://yiotis.net/filterizr/) is this note "If the height of your .filtr-item elements depends on images then you might have trouble, because their loading might be slow the height of your items might be messed up. To solve this issue you can either set the height of your images explicitly..."

I tried adding "height:100%" to [portfolio.html](https://github.com/themefisher/meghna-hugo/blob/master/layouts/partials/portfolio.html#L30), and that seems to fix the problem, at least for the moment. I'm not sure if this is a general solution but what to mention in case this helps other people.
`<img class="img-fluid" src="{{ .image | absURL}}" alt="work-image" height:100%>`

**Comment by Somrat37** [comment]
@kathrynloving , thanks for your concern.
