### ISSUE TITLE
can't change background images

### ISSUE THREAD

**Issue by hanna-del-rae** [themefisher/meghna-hugo#45]
I have been unable to change the background images of my site using this theme, even by adding my images to the same folder and using the same name as used in the toml file. 

I used `hero-area.jpg` and placed it in theme>static>images>slider.

Same issue with the "about us" background images by placing them in theme>static>images>backgrounds and naming my image `bg-1.jpg`

**Comment by Somrat37** [comment]
hey @hanna-del-rae , did you cleared your browser cache and reload? sometimes browser cached your before image and show that.

**Comment by hanna-del-rae** [comment]
@Somrat37  that was the issue - thank you!

Do you know how I can change the opacity of the background image without changing the opacity of the whole hero area?
