### ISSUE TITLE
create pricing2 section

### ISSUE THREAD

**Issue by hanna-del-rae** [themefisher/meghna-hugo#47]
I need to lay out pricing section for multiple products.

To accomplish that - do I need to create a new partial pricing2.html, pricing2.yml and .pricing2 classes in `.css` or is it possible to modify the layout of the existing pricing partial to call more than one table?

If so, how do I assign the proper values to the added cards?

Thank you!

**Comment by Somrat37** [comment]
hey @hanna-del-rae , you don't need to duplicate everything. just duplicate the pricing.html section and after duplicate open this code and replace `.Site.Data.pricing` with `.Site.Data.pricing2` everywhere. then just duplicate the pricing.yml file and name it pricing2.yml. that's it.
