### ISSUE TITLE
yams files not working

### ISSUE THREAD

**Issue by hanna-del-rae** [themefisher/meghna-hugo#48]
I added the .yml file for the portfolio section. 

portfolio.yml and added the content from the example yaml in data in this repo. 

![Screenshot 2019-05-09 13 04 23](https://user-images.githubusercontent.com/45800443/57483042-ea988d00-725a-11e9-8451-62818812ba5e.png)

The section will not build and hugo server no longer builds. 

The error I get is: 

`ERROR 2019/05/09 12:57:10 "/volumes/code/web-development-consulting/adelyte/data/portfolio.yml:2:1": failed to unmarshal YAML: yaml: line 2: found a tab character that violates indentation`

`Error: Error building site: "/volumes/code/web-development-consulting/adelyte/data/portfolio.yml:2:1": failed to unmarshal YAML: yaml: line 2: mapping values are not allowed in this context`

**Comment by Somrat37** [comment]
hey @hanna-del-rae, for solving this error you need to select the code from second line to bottom, and press `shift+tab`. then save it and hugo serve again. this error will be solved.
and for more help you can hire us. we are available for hiring. thanks

**Comment by mehedi-sharif** [comment]
Hello @hanna-del-rae ,
It seems that you are posting issues you are facing to setup hugo with our theme and none of theme are our theme related issues . We maintain our repository issues for fixing our theme's bug not personal support. I would suggest you to post this kind of support in [hugo support forum ](https://discourse.gohugo.io/) to get more answers . And if you think we can help you out you can also hire us. 
Thanks
