### ISSUE TITLE
blog section title not displaying

### ISSUE THREAD

**Issue by hanna-del-rae** [themefisher/meghna-hugo#49]
The latest blog posts section is working just fine with the exception of the heading and headingSpan not displaying. 

![Screenshot 2019-05-16 11 04 55](https://user-images.githubusercontent.com/45800443/57884577-cb12de80-77dd-11e9-996f-1d3bf4d5e8e5.png)

Below I show what my files currently look like, which I believe is how they should be.  Am I missing something or is there an error in the theme preventing the rendering of the title? 

![Screenshot 2019-05-16 11 05 09](https://user-images.githubusercontent.com/45800443/57884581-cea66580-77dd-11e9-8f12-39e56ddfcf62.png)

![Screenshot 2019-05-16 11 05 17](https://user-images.githubusercontent.com/45800443/57884586-d0702900-77dd-11e9-9bc7-69249635996d.png)

**Comment by Somrat37** [comment]
hey @hanna-del-rae , this is not an issue. you must missing something. you can see the [demo](https://themes.gohugo.io/theme/meghna-hugo/#blog). it works fine.
