### ISSUE TITLE
Font Family

### ISSUE THREAD

**Issue by SerhatTeker** [themefisher/meghna-hugo#51]
First of all, great theme. Thanks a lot. I'd like to ask: How can we change the font family? Couldn't find related field in `config.toml` —if exists. I can not use some `non-english` chars in `headings`. Rendering strangely.

**Comment by SerhatTeker** [comment]
I think it can be changed in `style.css` or adjusted in `custom.css` ?

**Comment by Somrat37** [comment]
hey @SerhatTeker , you can change font-family from style.css

**Comment by SerhatTeker** [comment]
hey @Somrat37. thanks a lot!
