### ISSUE TITLE
a blog-like section

### ISSUE THREAD

**Issue by vistad** [themefisher/meghna-hugo#52]
Hello guys, thank you for your great work! If I use Meghna theme and want to create another blog-like section - e.g. Tutorials, how do I do it? 
I copied blog section partial and inserted it into the page. I managed to give it a new name - Tutorials - but it still shows articles from /content/blog folder. How to configure it to show articles from /content/posts or /content/tutorials section?

**Comment by Somrat37** [comment]
If you have questions or need help integrating the product please [contact us](mailto:themefisher@gmail.com) instead of opening an issue.

**Comment by vistad** [comment]
I've solved the issue.
