### ISSUE TITLE
Closing `body` and `html` tags are duplicated at the bottom of the page

### ISSUE THREAD

**Issue by csarnataro** [themefisher/meghna-hugo#56]
I just noticed that the closing`</body></html>` tags are duplicated at the end of the page.

Steps to reproduce:
* go to 
  * https://themes.gohugo.io/theme/meghna-hugo/ or 
  * https://themes.gohugo.io//theme/meghna-hugo/post/
* view the source of the page 
  * view-source:https://themes.gohugo.io//theme/meghna-hugo/ or
  * view-source:https://themes.gohugo.io//theme/meghna-hugo/post/
* scroll to the bottom of the page
* check that the closing tags `</body></html>` are duplicated
See also this screenshot:
<img width="201" alt="Screenshot 2019-07-22 at 19 35 40" src="https://user-images.githubusercontent.com/11388820/61652665-c32d5a00-acb8-11e9-8bdb-ef9d3b3a3ebb.png">

I think this issue is caused by the partial https://github.com/themefisher/meghna-hugo/blob/master/layouts/partials/footer.html which includes `</body></html>`, which are already included in https://github.com/themefisher/meghna-hugo/blob/master/layouts/_default/baseof.html

I will send a simple PR for fixing this.

**Comment by Somrat37** [comment]
@csarnataro , thanks for your concern, i marge this pull request .
