### ISSUE TITLE
Broken .social-icon 

### ISSUE THREAD

**Issue by PhilmacFLy** [themefisher/meghna-hugo#58]
The .social-icon class in the css seems to be broken, as the social icons are disappearing behind the footer.
This is not only the case for my personal site but also for the Demo page.
![image](https://user-images.githubusercontent.com/139338/61801366-ebd76000-ae2e-11e9-80f2-adcb1f6d2e0a.png)

**Comment by hawkeye116477** [comment]
I don't have that problem. Maybe you are using some Adblock with Social list.

**Comment by PhilmacFLy** [comment]
You were right. It was my adblocker, sorry about that.
