### ISSUE TITLE
Social icons in the footer not loading on Safari

### ISSUE THREAD

**Issue by DragosDreptate** [themefisher/meghna-hugo#59]
Hi,

The socials icons in the footer are not displaying correctly (font not loading, cf attachement) on Safari browser (MacOS) when viewing the demo page https://themes.gohugo.io/theme/meghna-hugo/

Same bug on my website using Megna theme. 

Everything works perfect with Chrome on the same machine.

Any ideas?

Thank you

![Capture d’écran 2019-08-05 à 12 15 22](https://user-images.githubusercontent.com/35966620/62457714-aba3a600-b77b-11e9-93fc-331e8086f942.png)

**Comment by DragosDreptate** [comment]
Any ideas?

**Comment by plamenpetkov8** [comment]
@DragosDreptate Checked if you are using some king of Adblocker with what browser?

**Comment by DragosDreptate** [comment]
@plamenpetkov8 Checked, that's not the issue.
Any other idea? 
Thanks

**Comment by plamenpetkov8** [comment]
@DragosDreptate are there any errors being thrown in the Console log of the DevTools section of your browser?

**Comment by DragosDreptate** [comment]
@Somrat37 why did you close this issue? I still have the bug (and other people have it) on Safari MacOS on https://themes.gohugo.io/theme/meghna-hugo/

**Comment by Somrat37** [comment]
@DragosDreptate ,
i am sorry about this, your problem has been solved, please pull the latest code.

**Comment by DragosDreptate** [comment]
@Somrat37 the fix was deployed on https://themes.gohugo.io/theme/meghna-hugo/ ?
Because on my side the problem is still there when I navigate to that page with Safari

**Comment by Somrat37** [comment]
@DragosDreptate ,
No, it's not deployed yet, it will takes 2 or 3 days to deploy on hugo themes site, but you can download the repository and run it on your localhost to see the changes.
