### ISSUE TITLE
How to disable Meghna theme countdown in the "Hero" Area

### ISSUE THREAD

**Issue by Witenite** [themefisher/meghna-hugo#60]
Hi,

I have started using your Meghna theme for a business I'm just getting off the ground. I really do like your Hugo theme and would like to use it. At the moment I am using your example site as my template, adding/changing information as required to suit my purposes. I see the example site has a countdown in it (countdown variables also found in the config.toml file). How do I disable and hide the countdown altogether, as I really don't need it?

Thanks again for an otherwise fantastic theme.

Kind regards,
Graham Ward

**Comment by Somrat37** [comment]
hey @Witenite , Open `config.toml` file, and you can find a section called counter, simply change the enable value from `true` to `false`. it will be disabled

**Comment by Witenite** [comment]
Hi Somrat,
thanks for your reply. there is no section called counter though. The only reference I see is under the Hero Area, where there are 3 variables (countdownYear, countdownMonth, countdownDay). In this section called Hero Area, there is an option set as "enable = true". However if I set that to false, it completely reformats the webpage and I lose a lot of the styling that I need from the theme, so this is obviously the wrong setting.

Do I need to add a counter section to the config.toml file perhaps? You can see what I am talking about if you look at the exampleSite for the theme (where there is no counter section).

Thank you.
Graham

**Comment by Witenite** [comment]
ah, sorry, I have been an idiot and posted this question for the wrong theme! I meant to post this for your Infinity-Hugo theme.

Sorry guys.
