### ISSUE TITLE
Issue regarding the "Blog" section in the demo of the HUGO compatible Meghna theme 

### ISSUE THREAD

**Issue by plamenpetkov8** [themefisher/meghna-hugo#62]
There is some strange error being thrown in the console log of the browser upon visiting any of the content of the ["Blog" section](https://themes.gohugo.io//theme/meghna-hugo/#blog) of the demo of the HUGO compatible Meghna theme (tried it on **Chrome** (Version 74.0.3729.169 (Official Build) (64-bit)), **Firefox**(60.7.2esr (64-bit)) and **Opera** (Version:58.0.3135.68)). This "issue" occurs even if I am running my own HUGO project locally having applied that theme. Although "the error" is not breaking the interface, it's rather annoying. I think there could be some issue with the "filterzr" plugin.  
  
![Spectacle h13977](https://user-images.githubusercontent.com/17933466/67002661-0eeb7600-f0e5-11e9-804f-189083ced278.png)

**Comment by plamenpetkov8** [comment]
Debugging it even further, I found that the problem comes from the ./assets/js/script.js (starting point is considered the root of the theme). Narrowing it even more, it turned out that the issue is caused by the following lines of code:  
1. Line 54: "var filterizd = $('.filtr-container').filterizr({});"  
2. Line 291: "google.maps.event.addDomListener(window, "load", initialize);"

**Comment by Somrat37** [comment]
@plamenpetkov8 
thanks for your concern, i fixed the filter console error, and when you will provide a valid gmap API key, then the map error will automatically gone.
