### ISSUE TITLE
Unable to figure out how I can add an embedded YouTube video to a page.

### ISSUE THREAD

**Issue by Woutdb** [themefisher/meghna-hugo#63]
I stumbled upon this theme while deciding a theme for my hugo site and I liked it very much. However, I kind of want to put an embedded video on the website. As of yet, I haven’t figured out how I can do this.

Can someone explain/help me out here?

**Comment by plamenpetkov8** [comment]
If you are trying to add it in a markdown file, try this ["cheat"](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#youtube-videos).  
If you are trying to add it directly in your html partial, check this [tutorial](https://www.w3schools.com/html/html_youtube.asp).
