### ISSUE TITLE
Blog preview is broken

### ISSUE THREAD

**Issue by kanekotic** [themefisher/meghna-hugo#64]
the blog section is not displaying anymore the part related to the blog but showing now all the pages

**Comment by plamenpetkov8** [comment]
@kanekotic my guess is that you have to modify the **blog.html** partial that could be found in ./layouts/partial/ (starting point is considered the root directory of the theme)

**Comment by Somrat37** [comment]
hey @kanekotic , thanks for your concern, this issue has been fixed, you can pull the latest code.
