### ISSUE TITLE
Changing icons

### ISSUE THREAD

**Issue by UDROPS** [themefisher/meghna-hugo#68]
Hi, if I want to change the icons in the theme, how can I do that?

I found this part in the code: /Users/liviak/Library/Containers/com.apple.mail/Data/Library/Mail Downloads/C8FBF1E8-0441-46F0-B236-A1E22420C9F8/PastedGraphic-1.png

/Users/liviak/Library/Containers/com.apple.mail/Data/Library/Mail Downloads/7FD3248C-9391-4347-AE64-0F38569AC40D/PastedGraphic-2.png

**Comment by UDROPS** [comment]
it's in the about.yml:

enable : true
heading : About
headingSpan : Us
aboutItem : 
- icon : tf-tools
  title : We're Creative
  content : We are innovation driven, we listen to your ideas and we try to combine expertise in different fields to have a bigger impact.

- icon : tf-strategy
  title : We're Passionate
  content : Our team has a passion for water, we believe it's the most important resource in the world and we are trying to democratise it.

- icon : tf-anchor2
  title : We're Professionals
  content : We have a range of experiences thanks to our presence both in industry and academia. Please contact us for more info.

**Comment by Somrat37** [comment]
@UDROPS 
you want to change the icon or icon font?

**Comment by UDROPS** [comment]
the icon itself

**Comment by Somrat37** [comment]
@UDROPS 
download the latest code and go to `themes/static/plugins/themefisher-font/` then you can see `demo.html` file, open it in your browser and you can use icons from there what you need to use, thanks
