### ISSUE TITLE
Change color scheme

### ISSUE THREAD

**Issue by MarvinKweyu** [themefisher/meghna-hugo#70]
Currently, the scheme has a 'blue' feel to it. Is there a way to change it to the desired color possibly with a one-liner instead of going through the CSS files and manually looking through for class names to focus on?

**Comment by nguyenvienkt** [comment]
Following

**Comment by Somrat37** [comment]
Actually there is no other way, but you can do it in a simple way, open the css, find the color code and replace all  with your new color code. that is simple and one minute work.

**Comment by MarvinKweyu** [comment]
So would this be equivalent to manually editing the `theme`? Can this be done via the `custom CSS` option?

**Comment by Somrat37** [comment]
If you want to write custom css, then you need to find all the class name which has using this color. it would be very painful, the most easy way is replace the color code. it's very easy and simple

**Comment by MarvinKweyu** [comment]
Got it working as so

> Actually there is no other way, but you can do it in a simple way, open the css, find the color code and replace all with your new color code. that is simple and one minute work.

So would this affect any future theme update?

**Comment by Somrat37** [comment]
we are not planning about this. it would work if we add scss instead of css. but we don't have a plan to add scss in this template. but if you give me your color code, i can change it on main css, and will send you the css file.

**Comment by MarvinKweyu** [comment]
Ahh, I see. No need to worry about it as of now,

> Got it working as so

Updated the theme `CSS` with the scheme I needed.

**Comment by Qauzativ** [comment]
Please point to the CSS file where the background colours of the homepage should be tweaked, and which colours (sections of the homepage) it is advisable to change to make the theme less dark. There are several CSS files. Is it the 'style.css' file located in `assets/css/style.css`?
