### ISSUE TITLE
How to enable multilanguage support

### ISSUE THREAD

**Issue by thetrynix** [themefisher/meghna-hugo#71]
Hello there,

I plan to use this theme in multiple languages (as per https://gohugo.io/content-management/multilingual/ ). Is the theme ready, or are there any manual work I need to do to enable multi language for the theme?

Thanks.

**Comment by Somrat37** [comment]
@thetrynix 

This theme is multilingual supported. But not fully multilingual optimized. You can only see the multilingual in blog pages.

**Comment by thetrynix** [comment]
Hello,

Thank you for your response. My aim is to have the one-page homepage (which is a company profile) be in 2 languages. What adjustments must I make and where to make this happen. Would appreciate any advice.

Thank you.

**Comment by doorm4k3r** [comment]
Hello @Somrat37, @thetrynix 
I try to do multilanguage as well.
I have tried a few things (see below), nothing worked.
Based on the official documentation (https://gohugo.io/content-management/multilingual/)

I added

```
[languages]
  [languages.en]
    title = "My blog"
    weight = 1
    [languages.en.params]
      linkedin = "https://linkedin.com/whoever"
  [languages.fr]
    title = "Mon blogue"
    weight = 2
    [languages.fr.params]
      linkedin = "https://linkedin.com/fr/whoever"
      [languages.fr.params.navigation]
        help = "Aide"
```
to my config.toml and it seems to work.

However, if I try to make my about page multilanguage I am not able to do it.
* I tried to create two about.yml pages, like __about.yml__ and __about.fr.yml__, but if I checked http://localhost/fr, still the English about page was rendered.

* I tried to set __contentDir = "data/en"__ and __contentDir = "data/fr"__ in the corresponding language section and create two about pages in the data/en and data/fr directories. In this scenario, the about page never rendered.

Do I miss something?

Thank you for the feedback:
David

**Comment by Somrat37** [comment]
@thetrynix, @doorm4k3r 

This theme is now supports multilingual, please download the latest code.
