### ISSUE TITLE
Mixed content in theme demo

### ISSUE THREAD

**Issue by onedrawingperday** [themefisher/meghna-hugo#72]
Hello @Somrat37 

In the latest deploy of Hugo themes there is the following warning:

```
2:16:55 AM: Mixed content detected in: /meghna-hugo/index.html
2:16:55 AM: --> insecure img urls:
2:16:55 AM:   - http://img.youtube.com/vi/DbZKmZIPBLg/0.jpg
```
Please change the protocol used in the above link to `https`.
Always use `https` when serving external assets in a theme demo.

Once you fix this, feel free to close this issue.

**Comment by Somrat37** [comment]
this issue has been fixed
