### ISSUE TITLE
Old Meghna-Hugo theme not deploying

### ISSUE THREAD

**Issue by danmcsmith** [themefisher/meghna-hugo#74]
Hello,

I have been attempting to deploy the old Meghna-Hugo theme on Netlify for close to a week now and am at a dead end. I have been building my site based on the old theme due to beginning the website build before the theme was updated.

When I push to my repository (which has the old theme in it) to github, I get an exit code 1 and the file does not get pushed. 

With Netlify, I continue getting errors with Netlify, either 'exit code: 1' or '255'. I'm using the build command "cd thorove && hugo --gc --themesDir ../.." but Netlify is returning 'No such file or directory'. I'm guessing this is due to the theme folder not getting pushed to github. I've tried other build commands like the classic "hugo --gc --minify" found on the Hugo website as well as trying multiple variations of the netlify.toml to fit this theme and Hugo version. 

I attempted to look at the old full documentation but the site is down. I've tried many variations to try and push the theme folder up but no luck. I hope I don't have to rebuild the site using the new theme as this took awhile to build. 

I'm pretty new to the Hugo world so any help would be greatly appreciated.
Thanks,

**Comment by Somrat37** [comment]
@danmcsmith 

Please tell me that, can you run this template on your localhost?

**Comment by danmcsmith** [comment]
@Somrat37 
Yes, runs fine on localhost.

**Comment by Somrat37** [comment]
Ok, then clear the netlify.toml file and pase this new configuration.

`[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.54.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo  --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.54.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo  --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.54.0"

[context.branch-deploy]
command = "hugo  --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.54.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
`

**Comment by danmcsmith** [comment]
Thank you for that! I do believe that will work however I think it's not linking (forking?) to your repo correctly. Here's the error log:
'
9:27:02 PM: Waiting for other deploys from your team to complete
9:27:18 PM: Build ready to start
9:27:20 PM: build-image version: 9cade8af58c2cf3a17a1e9433d2e979149488837
9:27:20 PM: build-image tag: v3.3.5
9:27:20 PM: buildbot version: 2d05064ce3dd2eb95d282a24602ab707dd9581e8
9:27:20 PM: Fetching cached dependencies
9:27:21 PM: Failed to fetch cache, continuing with build
9:27:21 PM: Starting to prepare the repo for build
9:27:21 PM: No cached dependencies found. Cloning fresh repo
9:27:21 PM: git clone https://github.com/danmcsmith/thorove
9:28:01 PM: Preparing Git Reference refs/heads/master
9:28:02 PM: Found Netlify configuration file. Overriding site configuration
9:28:02 PM: Different build command detected, going to use the one specified in the Netlify configuration file: 'hugo --gc --minify' versus 'hugo --gc --minify -b $URL' in the Netlify UI
9:28:02 PM: Starting build script
9:28:02 PM: Installing dependencies
9:28:04 PM: Downloading and installing node v10.18.0...
9:28:04 PM: Downloading https://nodejs.org/dist/v10.18.0/node-v10.18.0-linux-x64.tar.xz...
9:28:04 PM: 
################
9:28:04 PM:                                 23.0%
9:28:04 PM: 
############################################################
9:28:04 PM: ############ 100.0%
9:28:04 PM: Computing checksum with sha256sum
9:28:05 PM: Checksums matched!
9:28:08 PM: Now using node v10.18.0 (npm v6.13.4)
9:28:08 PM: Attempting ruby version 2.6.2, read from environment
9:28:10 PM: Using ruby version 2.6.2
9:28:10 PM: Using PHP version 5.6
9:28:10 PM: Installing Hugo 0.54.0
9:28:12 PM: Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
9:28:12 PM: Started restoring cached go cache
9:28:12 PM: Finished restoring cached go cache
9:28:12 PM: unset GOOS;
9:28:12 PM: unset GOARCH;
9:28:12 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
9:28:12 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
9:28:12 PM: go version >&2;
9:28:12 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
9:28:12 PM: go version go1.12 linux/amd64
9:28:12 PM: Installing missing commands
9:28:12 PM: Verify run directory
9:28:12 PM: Executing user command: hugo --gc --minify
9:28:12 PM: Error: Unable to find theme Directory: /opt/build/repo/themes/meghna-hugo
9:28:12 PM: Skipping functions preparation step: no functions directory set
9:28:12 PM: Caching artifacts
9:28:12 PM: Started saving pip cache
9:28:12 PM: Finished saving pip cache
9:28:12 PM: Started saving emacs cask dependencies
9:28:12 PM: Finished saving emacs cask dependencies
9:28:12 PM: Started saving maven dependencies
9:28:12 PM: Finished saving maven dependencies
9:28:12 PM: Started saving boot dependencies
9:28:12 PM: Finished saving boot dependencies
9:28:12 PM: Started saving go dependencies
9:28:12 PM: Finished saving go dependencies
9:28:15 PM: Error running command: Build script returned non-zero exit code: 255
9:28:15 PM: Failing build: Failed to build site
9:28:15 PM: failed during stage 'building site': Build script returned non-zero exit code: 255
9:28:15 PM: Finished processing build request in 54.869848458s
'
I'm unable to commit the theme from my local repo to the github repo. I get the same error of "error code 1" when I attempt to add and commit the theme to my github repo. It is themefisher's old megnha repo that won't commit.
Any suggestions?
Thanks again for your help!

**Comment by Somrat37** [comment]
I checked your repository https://github.com/danmcsmith/thorove , but there is no themes folder. if you are talking about old meghna hugo theme, there was a themes folder which is missing in your repository. that's why it is not deploying with netlify.

**Comment by danmcsmith** [comment]
Thank you for checking. That is exactly the problem I was trying to tell you from the beginning. The theme folder is not committing to the repository. I continue to get an error code 1 when trying to commit the themes folder. Please see screenshot below.

![github error code](https://user-images.githubusercontent.com/56140106/71591770-701ac700-2ae2-11ea-883b-2484166f83da.jpg)

Thanks again for your help Somrat!

**Comment by Somrat37** [comment]
ok, i got your problem. now follow the steps. go to the themes folder and show hidden file from your pc. now you can see a .git folder which is hidden in themes folder. simply delete this folder, and go back to your root folder. then command `git add --all` and then make a commit and push. your problem will be solved

**Comment by themefisherDev** [comment]
@danmcsmith , did you solve it? i am going to close this issue, if you have any problem left, don't hesitate  to reopen this issue.

**Comment by danmcsmith** [comment]
No, that didn't work. Please do not close. I'm trying something with the .gitmodules (it worked on another site I'm building). I'm out of town this weekend so please leave open till Monday. Thank you

**Comment by danmcsmith** [comment]
Thank you for keeping this open. I finally figured out how to upload the themes folder (not exactly sure what the problem was so I just started over with a new repo). I have a new probelm, however, the site generated does not style the website. I will attach an image of the public site rendered below:
![thorove css problem](https://user-images.githubusercontent.com/56140106/73094356-41033580-3e95-11ea-9be0-773daf4db8ef.jpg)

You can look at my repo here: https://github.com/danmcsmith/thorove

Thank you for your help!
~Dan

**Comment by themefisherDev** [comment]
Thats because your base url does not match. this is what you can do
1. copy the site url
2. edit your config.toml file.
3. replace this baseURL
4. make a push.
