### ISSUE TITLE
easy way to center the blocks?

### ISSUE THREAD

**Issue by jeremyatia** [themefisher/meghna-hugo#77]
Hi,
I would like to know a simple way to center the blocks in the theme.
More precisely the blocks "Team" and "Portfolio".
_Example of the block ["Team"](https://themes.gohugo.io/theme/meghna-hugo/)_
if you have less than 4 people in the team, they appear aligned on the left..
Do you have any idea?
Thanks,
Jeremy

**Comment by themefisherDev** [comment]
Hey,

Just put the `justify-content-center` class name with `row` class.

**Comment by jeremyatia** [comment]
Hi @themefisherDev,
I know you can change directly the html.
Unfortunately if I build again the website (using the command `hugo` ) the change you just mentioned will be gone.
Do you have a way to fix that?

**Comment by themefisherDev** [comment]
hey there, make the change before you running hugo. it will not be gone.

**Comment by jeremyatia** [comment]
> Hey,
> 
> Just put the `justify-content-center` class name with `row` class.

When you say that you mean to edit the index.html file in the public folder or the change should be done somewhere else?

**Comment by themefisherDev** [comment]
Hey,
 I made an update including fixes your issue, take a pull.

**Comment by jeremyatia** [comment]
@themefisherDev thanks for the effort in fixing, I did pull.
It seems like the change you did affects another `<div>`, as shown here:
```html
<!-- Start Our Team -->
<section id="team" class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 justify-content-center">
```
I guess it should be in the upper class, next to `row` as you mentioned above.
