### ISSUE TITLE
easy way to center the blocks 

### ISSUE THREAD

**Issue by jeremyatia** [themefisher/meghna-hugo#81]
@themefisherDev  thanks for the effort in fixing, I did pull.
You closed the issue #77 but it seems like the change you did affects another < div class [...]>, as shown here:
``` html
<!-- Start Our Team -->
<section id="team" class="section">
  <div class="container">
    <div class="row">  <!-- 'justify-content-center' not here -->
      <div class="col-lg-12 justify-content-center">  <!-- but here  -->
```
_So the block "Team" is still not centered_
I guess it should be in the class, next to `row` as you mentioned in the issue #77?

**Comment by themefisherDev** [comment]
@jeremyatia ,

Hey thanks for your concern. it was a mistake. i fixed that.

**Comment by jeremyatia** [comment]
Thanks @themefisherDev, much appreciated!
