### ISSUE TITLE
Portfolio section overlapping images on initial page load.

### ISSUE THREAD

**Issue by OmNomNomagon** [themefisher/meghna-hugo#82]
Hello,

I am having a reoccurring issue where the images in the portfolio section overlap each other as seen in the picture below. It occurs on the initial loading of the page. However, as soon as the browser window is maximized or resized, the images immediately reflow into their proper grid locations.

sometimes it happens to a few of the images, but other times it affects every image.

![OverlapIssue](https://user-images.githubusercontent.com/7193108/74794863-83932300-5318-11ea-9f3a-fbe67cc40283.JPG)

**Comment by themefisherDev** [comment]
are you using the latest update version?

**Comment by OmNomNomagon** [comment]
Yes, I pulled the newest version

**Comment by themefisherDev** [comment]
I made another update after that, please pull this...
