### ISSUE TITLE
With a Single Blog post - Author shows up in Latest Posts Section

### ISSUE THREAD

**Issue by petersellars** [themefisher/meghna-hugo#84]
With a Single Blog Post - my initial blog post added to this theme - the Author I have created also appears in the Latest Posts section. If I select `View All Posts` the Author disappears. I believed this was using the same code so trying to understand how I can not get the Author to show in the initial loaded Blogs for Latest Posts.

**Comment by petersellars** [comment]
If I update this line in `layout/partials/blog.html`

```
{{ range first 3 .Site.RegularPages }}
```

to

```
{{ range first 3 (where .Site.RegularPages "Section" "==" "blog")}}
```

I get the expected result and no Authors are shown, List all works too.

**Comment by petersellars** [comment]
Authors only show if there are less than 3 blog posts so this will only affect people with less than 3 blog posts, but it is stopping me from publishing at the moment, as don't want to see the Author on the front page. :)

I tested with the example site and got the same result when removed all the blog posts.

This fixes the issue and the latest post behaviour does not change. Am no Hugo expert though, so don't know if this is a good fix or not!

**Comment by themefisherDev** [comment]
Yes, you can do this. It's a good fix.

**Comment by petersellars** [comment]
> Yes, you can do this. It's a good fix.

@themefisherDev - Should I submit this as a pull request?

**Comment by themefisherDev** [comment]
You can make a pull request if you want. or i will fix this in the next update. thanks
