### ISSUE TITLE
No style

### ISSUE THREAD

**Issue by recasanova** [themefisher/meghna-hugo#85]
Hi, I did all the steps and the layout is broken and not showing. Please advice
![Screen Shot 2020-02-24 at 5 11 54 PM](https://user-images.githubusercontent.com/15710308/75205527-dd388a80-5728-11ea-8a6c-0a6be29d88ba.png)

**Comment by themefisherDev** [comment]
is it on your localhost or on a server?

**Comment by aesopos** [comment]
same issue 
--> server using netlify
