### ISSUE TITLE
Portfolio category selection breaks with scroll

### ISSUE THREAD

**Issue by joshmcfayden** [themefisher/meghna-hugo#89]
Hi,

The category (e.g. "Design")  selection in the portfolio section works fine on an initial click, but then if I scroll down the page it re-loads all portfolio items, not just those from the selected category. Seems to happen on the demo page for Chrome and Safari at least.

Best regards,

Josh

**Comment by themefisherDev** [comment]
Hey, thanks for your concern, it was an issue. i fixed it. please pull the latest code.
