### ISSUE TITLE
Static link to Menu

### ISSUE THREAD

**Issue by namkyodai** [themefisher/meghna-hugo#91]
Dear Meghan team,
I was trying to make a new menu and set a static link to it. but couldnt figure it out. Can you please help.

For example, in the config.toml

i created

[[menu.main]]
name = "Library"
url  = "library/library.md"
weight = 5

--> the library folder is created under content/english --> similar to that of blog.

Is there anyway to link directly to a md file.

Thanks

Nam

**Comment by Somrat37** [comment]
hey, thanks for your concern, i made an update for this template. please pull the latest code and create your static menu like 
`
[[menu.static]]
name = "Library"
url = "library"
weight = 5
`

**Comment by namkyodai** [comment]
Thanks Somrat37 for the update. 
is this method also work for service.yml file?

For example, under service, I insert URL URL: "blog/simple-blog-post-1", however, it seems not working when moving the mouse over the section under service,
  # service item loop
    - name : Media &amp; Advertisement
      icon : ti-blackboard # themify icon pack : https://themify.me/themify-icons
      content : Lorem ipsum dolor sit amet, consectetur.. Sed id lorem eget orci dictum facilisis vel id tellus.Nullam iaculis arcu at mauris dapibus consectetur.
      URL: "blog/simple-blog-post-1"

Nam
