### ISSUE TITLE
How to enable multilanguage main menu ?

### ISSUE THREAD

**Issue by dleguyader** [themefisher/meghna-hugo#92]
Hello there, 

First thank for this great work!

I plan to built a multilingual website with this theme. I have managed to create content in both english and french for exemple. However, I am stucked with creating a main menu changing from English to French. Following instruction from https://gohugo.io/content-management/multilingual/, the main menu disappear...
I have read similar issues solved, but without success.
Would appreciate any advice.

Thank you.

**Comment by dleguyader** [comment]
Hello, 

I have just resolve my problem. Sorry, for that and again thank you for this work.

**Comment by liguanghe** [comment]
> Hello,
> 
> I have just resolve my problem. Sorry, for that and again thank you for this work.

@dleguyader may i ask how to solve this problem~? i mate the same problem.
