### ISSUE TITLE
Drop down menu

### ISSUE THREAD

**Issue by dleguyader** [themefisher/meghna-hugo#94]
Dear Meghna team,

I am trying to create a drop down menu according to these [instructions ](https://documentation.themefisher.com/docs/meghna-hugo/navigation/) but I can't figure it out. Can you please help?

_In the config.toml_: 

[[Languages.en.menu.main]]
name = "About"
URL = "about"
weight = 1

[[Languages.en.menu.main]]
name = "Our services"
weight = 2
URL = "services"

[[Languages.en.menu.main]]
HasChildren = true 
*(with tab)* [Languages.en.menu.main]]
*(with tab)* parent = "Our services"
*(with tab)* name = "Service n°1"
*(with tab)* URL = "content/services/services1"

The services1 file is an *.md* file

Thanks

Damien

**Comment by Somrat37** [comment]
hey there, we are sorry to say that we removed this dropdown feature from this template because of it's a landing page template and it's scrollable behavior.
