### ISSUE TITLE
Preloader not vanishing on Safari 9 mobile

### ISSUE THREAD

**Issue by OlafHaag** [themefisher/meghna-hugo#96]
Hey! The only Apple device I have laying around for testing the website is an old iPad mini 1 which as Safari 9 as a browser.

When visiting the [theme's demo site](http://demo.themefisher.com/meghna-hugo/) (or my own site using meghna, for that matter), the preloader isn't disappearing. The loaded website is behind it.

I could imagine that other Safari versions are affected as well.

**Comment by Somrat37** [comment]
Hey there, I made an update of this theme, please take a pull and try again, thanks.

**Comment by OlafHaag** [comment]
This does the trick! Thanks!
