### ISSUE TITLE
Wildly uneven lengths for blog posts list

### ISSUE THREAD

**Issue by fvlasie** [themefisher/meghna-hugo#98]
<img width="150" alt="Screen Shot 2020-05-07 at 2 57 28 PM copy" src="https://user-images.githubusercontent.com/33334298/81348666-57fc1b00-9073-11ea-97bc-2ae6a6f29a80.png">
Hello,
As you can see in the screenshot the lengths of the blocks is really uneven. What code is controlling the truncation?

Thank you for a really nice theme!

FV

**Comment by Somrat37** [comment]
hey there, you can see `summerylength` in config.toml file. it handles the truncate,

https://github.com/themefisher/meghna-hugo/blob/f8047590d8ef0d2676f7aebfb8aaf68e7bfcd434/exampleSite/config.toml#L8
