### ISSUE TITLE
Language default 'en'

### ISSUE THREAD

**Issue by ajoyac** [themefisher/meghna-hugo#99]
I Im  trying to create a website without english option, but default ask me to created,

**Comment by Somrat37** [comment]
you can follow this instruction 
https://gohugo.io/content-management/multilingual/

**Comment by ajoyac** [comment]
yeah this works except for the form fields.

**Comment by somrat-gyver** [comment]
Hey there, I fixed this issue, now you will have a fully translated site. please download the latest code. thanks for being with themefisher.
